package com.xceder.ctp.thostftdcuserapistruct;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * \u7528\u6237\u767b\u5f55\u8bf7\u6c42<br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
public class CThostFtdcReqUserLoginField extends StructObject {
	public CThostFtdcReqUserLoginField() {
	}

	@Array({9L})
	@Field(0)
	private Pointer<Byte> TradingDay() {
		return this.io.getPointerField(this, 0);
	}

	@Array({9L})
	@Field(0)
	public void setTradingDay(String tradingDay) {
		this.io.getPointerField(this, 0).setCString(tradingDay);
	}

	public String getTradingDay() {
		return this.TradingDay().getCString();
	}

	@Array({11L})
	@Field(1)
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({11L})
	@Field(1)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 1).setCString(brokerID);
	}

	public String getBrokerID() {
		return this.BrokerID().getCString();
	}

	@Array({16L})
	@Field(2)
	private Pointer<Byte> UserID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({16L})
	@Field(2)
	public void setUserID(String userID) {
		this.io.getPointerField(this, 2).setCString(userID);
	}

	public String getUserID() {
		return this.UserID().getCString();
	}

	@Array({41L})
	@Field(3)
	private Pointer<Byte> Password() {
		return this.io.getPointerField(this, 3);
	}

	@Array({41L})
	@Field(3)
	public void setPassword(String password) {
		this.io.getPointerField(this, 3).setCString(password);
	}

	public String getPassword() {
		return this.Password().getCString();
	}

	@Array({11L})
	@Field(4)
	private Pointer<Byte> UserProductInfo() {
		return this.io.getPointerField(this, 4);
	}

	@Array({11L})
	@Field(4)
	public void setUserProductInfo(String userProductInfo) {
		this.io.getPointerField(this, 4).setCString(userProductInfo);
	}

	public String getUserProductInfo() {
		return this.UserProductInfo().getCString();
	}

	@Array({11L})
	@Field(5)
	private Pointer<Byte> InterfaceProductInfo() {
		return this.io.getPointerField(this, 5);
	}

	@Array({11L})
	@Field(5)
	public void setInterfaceProductInfo(String interfaceProductInfo) {
		this.io.getPointerField(this, 5).setCString(interfaceProductInfo);
	}

	public String getInterfaceProductInfo() {
		return this.InterfaceProductInfo().getCString();
	}

	@Array({11L})
	@Field(6)
	private Pointer<Byte> ProtocolInfo() {
		return this.io.getPointerField(this, 6);
	}

	@Array({11L})
	@Field(6)
	public void setProtocolInfo(String protocolInfo) {
		this.io.getPointerField(this, 6).setCString(protocolInfo);
	}

	public String getProtocolInfo() {
		return this.ProtocolInfo().getCString();
	}

	@Array({21L})
	@Field(7)
	private Pointer<Byte> MacAddress() {
		return this.io.getPointerField(this, 7);
	}

	@Array({21L})
	@Field(7)
	public void setMacAddress(String macAddress) {
		this.io.getPointerField(this, 7).setCString(macAddress);
	}

	public String getMacAddress() {
		return this.MacAddress().getCString();
	}

	@Array({41L})
	@Field(8)
	private Pointer<Byte> OneTimePassword() {
		return this.io.getPointerField(this, 8);
	}

	@Array({41L})
	@Field(8)
	public void setOneTimePassword(String oneTimePassword) {
		this.io.getPointerField(this, 8).setCString(oneTimePassword);
	}

	public String getOneTimePassword() {
		return this.OneTimePassword().getCString();
	}

	@Array({16L})
	@Field(9)
	private Pointer<Byte> ClientIPAddress() {
		return this.io.getPointerField(this, 9);
	}

	@Array({16L})
	@Field(9)
	public void setClientIPAddress(String clientIPAddress) {
		this.io.getPointerField(this, 9).setCString(clientIPAddress);
	}

	public String getClientIPAddress() {
		return this.ClientIPAddress().getCString();
	}

	public CThostFtdcReqUserLoginField(Pointer pointer) {
		super(pointer);
	}
}
