package com.xceder.ctp.thostftdcuserapistruct;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * \u6295\u8d44\u8005\u6301\u4ed3\u660e\u7ec6<br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
public class CThostFtdcInvestorPositionDetailField extends StructObject {
	public CThostFtdcInvestorPositionDetailField() {
	}

	@Array({31L})
	@Field(0)
	private Pointer<Byte> InstrumentID() {
		return this.io.getPointerField(this, 0);
	}

	@Array({31L})
	@Field(0)
	public void setInstrumentID(String instrumentID) {
		this.io.getPointerField(this, 0).setCString(instrumentID);
	}

	public String getInstrumentID() {
		return this.InstrumentID().getCString();
	}

	@Array({11L})
	@Field(1)
	private Pointer<Byte> BrokerID() {
		return this.io.getPointerField(this, 1);
	}

	@Array({11L})
	@Field(1)
	public void setBrokerID(String brokerID) {
		this.io.getPointerField(this, 1).setCString(brokerID);
	}

	public String getBrokerID() {
		return this.BrokerID().getCString();
	}

	@Array({13L})
	@Field(2)
	private Pointer<Byte> InvestorID() {
		return this.io.getPointerField(this, 2);
	}

	@Array({13L})
	@Field(2)
	public void setInvestorID(String investorID) {
		this.io.getPointerField(this, 2).setCString(investorID);
	}

	public String getInvestorID() {
		return this.InvestorID().getCString();
	}

	@Field(3)
	private byte HedgeFlag() {
		return this.io.getByteField(this, 3);
	}

	public char getHedgeFlag() {
		return (char)this.HedgeFlag();
	}

	@Field(3)
	private CThostFtdcInvestorPositionDetailField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 3, HedgeFlag);
		return this;
	}

	public void setHedgeFlag(char hedgeFlag) {
		this.HedgeFlag((byte)hedgeFlag);
	}

	@Field(4)
	private byte Direction() {
		return this.io.getByteField(this, 4);
	}

	public char getDirection() {
		return (char)this.Direction();
	}

	@Field(4)
	private CThostFtdcInvestorPositionDetailField Direction(byte Direction) {
		this.io.setByteField(this, 4, Direction);
		return this;
	}

	public void setDirection(char direction) {
		this.Direction((byte)direction);
	}

	@Array({9L})
	@Field(5)
	private Pointer<Byte> OpenDate() {
		return this.io.getPointerField(this, 5);
	}

	@Array({9L})
	@Field(5)
	public void setOpenDate(String openDate) {
		this.io.getPointerField(this, 5).setCString(openDate);
	}

	public String getOpenDate() {
		return this.OpenDate().getCString();
	}

	@Array({21L})
	@Field(6)
	private Pointer<Byte> TradeID() {
		return this.io.getPointerField(this, 6);
	}

	@Array({21L})
	@Field(6)
	public void setTradeID(String tradeID) {
		this.io.getPointerField(this, 6).setCString(tradeID);
	}

	public String getTradeID() {
		return this.TradeID().getCString();
	}

	@Field(7)
	private int Volume() {
		return this.io.getIntField(this, 7);
	}

	public int getVolume() {
		return this.Volume();
	}

	@Field(7)
	private CThostFtdcInvestorPositionDetailField Volume(int Volume) {
		this.io.setIntField(this, 7, Volume);
		return this;
	}

	public void setVolume(int volume) {
		this.Volume(volume);
	}

	@Field(8)
	private double OpenPrice() {
		return this.io.getDoubleField(this, 8);
	}

	public double getOpenPrice() {
		return this.OpenPrice();
	}

	@Field(8)
	private CThostFtdcInvestorPositionDetailField OpenPrice(double OpenPrice) {
		this.io.setDoubleField(this, 8, OpenPrice);
		return this;
	}

	public void setOpenPrice(double openPrice) {
		this.OpenPrice(openPrice);
	}

	@Array({9L})
	@Field(9)
	private Pointer<Byte> TradingDay() {
		return this.io.getPointerField(this, 9);
	}

	@Array({9L})
	@Field(9)
	public void setTradingDay(String tradingDay) {
		this.io.getPointerField(this, 9).setCString(tradingDay);
	}

	public String getTradingDay() {
		return this.TradingDay().getCString();
	}

	@Field(10)
	private int SettlementID() {
		return this.io.getIntField(this, 10);
	}

	public int getSettlementID() {
		return this.SettlementID();
	}

	@Field(10)
	private CThostFtdcInvestorPositionDetailField SettlementID(int SettlementID) {
		this.io.setIntField(this, 10, SettlementID);
		return this;
	}

	public void setSettlementID(int settlementID) {
		this.SettlementID(settlementID);
	}

	@Field(11)
	private byte TradeType() {
		return this.io.getByteField(this, 11);
	}

	public char getTradeType() {
		return (char)this.TradeType();
	}

	@Field(11)
	private CThostFtdcInvestorPositionDetailField TradeType(byte TradeType) {
		this.io.setByteField(this, 11, TradeType);
		return this;
	}

	public void setTradeType(char tradeType) {
		this.TradeType((byte)tradeType);
	}

	@Array({31L})
	@Field(12)
	private Pointer<Byte> CombInstrumentID() {
		return this.io.getPointerField(this, 12);
	}

	@Array({31L})
	@Field(12)
	public void setCombInstrumentID(String combInstrumentID) {
		this.io.getPointerField(this, 12).setCString(combInstrumentID);
	}

	public String getCombInstrumentID() {
		return this.CombInstrumentID().getCString();
	}

	@Array({9L})
	@Field(13)
	private Pointer<Byte> ExchangeID() {
		return this.io.getPointerField(this, 13);
	}

	@Array({9L})
	@Field(13)
	public void setExchangeID(String exchangeID) {
		this.io.getPointerField(this, 13).setCString(exchangeID);
	}

	public String getExchangeID() {
		return this.ExchangeID().getCString();
	}

	@Field(14)
	private double CloseProfitByDate() {
		return this.io.getDoubleField(this, 14);
	}

	public double getCloseProfitByDate() {
		return this.CloseProfitByDate();
	}

	@Field(14)
	private CThostFtdcInvestorPositionDetailField CloseProfitByDate(double CloseProfitByDate) {
		this.io.setDoubleField(this, 14, CloseProfitByDate);
		return this;
	}

	public void setCloseProfitByDate(double closeProfitByDate) {
		this.CloseProfitByDate(closeProfitByDate);
	}

	@Field(15)
	private double CloseProfitByTrade() {
		return this.io.getDoubleField(this, 15);
	}

	public double getCloseProfitByTrade() {
		return this.CloseProfitByTrade();
	}

	@Field(15)
	private CThostFtdcInvestorPositionDetailField CloseProfitByTrade(double CloseProfitByTrade) {
		this.io.setDoubleField(this, 15, CloseProfitByTrade);
		return this;
	}

	public void setCloseProfitByTrade(double closeProfitByTrade) {
		this.CloseProfitByTrade(closeProfitByTrade);
	}

	@Field(16)
	private double PositionProfitByDate() {
		return this.io.getDoubleField(this, 16);
	}

	public double getPositionProfitByDate() {
		return this.PositionProfitByDate();
	}

	@Field(16)
	private CThostFtdcInvestorPositionDetailField PositionProfitByDate(double PositionProfitByDate) {
		this.io.setDoubleField(this, 16, PositionProfitByDate);
		return this;
	}

	public void setPositionProfitByDate(double positionProfitByDate) {
		this.PositionProfitByDate(positionProfitByDate);
	}

	@Field(17)
	private double PositionProfitByTrade() {
		return this.io.getDoubleField(this, 17);
	}

	public double getPositionProfitByTrade() {
		return this.PositionProfitByTrade();
	}

	@Field(17)
	private CThostFtdcInvestorPositionDetailField PositionProfitByTrade(double PositionProfitByTrade) {
		this.io.setDoubleField(this, 17, PositionProfitByTrade);
		return this;
	}

	public void setPositionProfitByTrade(double positionProfitByTrade) {
		this.PositionProfitByTrade(positionProfitByTrade);
	}

	@Field(18)
	private double Margin() {
		return this.io.getDoubleField(this, 18);
	}

	public double getMargin() {
		return this.Margin();
	}

	@Field(18)
	private CThostFtdcInvestorPositionDetailField Margin(double Margin) {
		this.io.setDoubleField(this, 18, Margin);
		return this;
	}

	public void setMargin(double margin) {
		this.Margin(margin);
	}

	@Field(19)
	private double ExchMargin() {
		return this.io.getDoubleField(this, 19);
	}

	public double getExchMargin() {
		return this.ExchMargin();
	}

	@Field(19)
	private CThostFtdcInvestorPositionDetailField ExchMargin(double ExchMargin) {
		this.io.setDoubleField(this, 19, ExchMargin);
		return this;
	}

	public void setExchMargin(double exchMargin) {
		this.ExchMargin(exchMargin);
	}

	@Field(20)
	private double MarginRateByMoney() {
		return this.io.getDoubleField(this, 20);
	}

	public double getMarginRateByMoney() {
		return this.MarginRateByMoney();
	}

	@Field(20)
	private CThostFtdcInvestorPositionDetailField MarginRateByMoney(double MarginRateByMoney) {
		this.io.setDoubleField(this, 20, MarginRateByMoney);
		return this;
	}

	public void setMarginRateByMoney(double marginRateByMoney) {
		this.MarginRateByMoney(marginRateByMoney);
	}

	@Field(21)
	private double MarginRateByVolume() {
		return this.io.getDoubleField(this, 21);
	}

	public double getMarginRateByVolume() {
		return this.MarginRateByVolume();
	}

	@Field(21)
	private CThostFtdcInvestorPositionDetailField MarginRateByVolume(double MarginRateByVolume) {
		this.io.setDoubleField(this, 21, MarginRateByVolume);
		return this;
	}

	public void setMarginRateByVolume(double marginRateByVolume) {
		this.MarginRateByVolume(marginRateByVolume);
	}

	@Field(22)
	private double LastSettlementPrice() {
		return this.io.getDoubleField(this, 22);
	}

	public double getLastSettlementPrice() {
		return this.LastSettlementPrice();
	}

	@Field(22)
	private CThostFtdcInvestorPositionDetailField LastSettlementPrice(double LastSettlementPrice) {
		this.io.setDoubleField(this, 22, LastSettlementPrice);
		return this;
	}

	public void setLastSettlementPrice(double lastSettlementPrice) {
		this.LastSettlementPrice(lastSettlementPrice);
	}

	@Field(23)
	private double SettlementPrice() {
		return this.io.getDoubleField(this, 23);
	}

	public double getSettlementPrice() {
		return this.SettlementPrice();
	}

	@Field(23)
	private CThostFtdcInvestorPositionDetailField SettlementPrice(double SettlementPrice) {
		this.io.setDoubleField(this, 23, SettlementPrice);
		return this;
	}

	public void setSettlementPrice(double settlementPrice) {
		this.SettlementPrice(settlementPrice);
	}

	@Field(24)
	private int CloseVolume() {
		return this.io.getIntField(this, 24);
	}

	public int getCloseVolume() {
		return this.CloseVolume();
	}

	@Field(24)
	private CThostFtdcInvestorPositionDetailField CloseVolume(int CloseVolume) {
		this.io.setIntField(this, 24, CloseVolume);
		return this;
	}

	public void setCloseVolume(int closeVolume) {
		this.CloseVolume(closeVolume);
	}

	@Field(25)
	private double CloseAmount() {
		return this.io.getDoubleField(this, 25);
	}

	public double getCloseAmount() {
		return this.CloseAmount();
	}

	@Field(25)
	private CThostFtdcInvestorPositionDetailField CloseAmount(double CloseAmount) {
		this.io.setDoubleField(this, 25, CloseAmount);
		return this;
	}

	public void setCloseAmount(double closeAmount) {
		this.CloseAmount(closeAmount);
	}

	public CThostFtdcInvestorPositionDetailField(Pointer pointer) {
		super(pointer);
	}
}
